language: csharp
solution: MajorsilenceReporting-Linux.sln
install:
  - sudo apt-get install mono-devel mono-gmcs mono-dmcs nunit-console libpoppler-cil xvfb libgtk2.0-cil libpoppler-cil nuget
 
script:
  - nuget restore ./MajorsilenceReporting-Linux.sln -NonInteractive
  - xbuild /p:Configuration=Release MajorsilenceReporting-Linux.sln
  - nunit-console ./ReportTests/bin/Release/ReportTests.dll -exclude Integration,NotWorkingOnMono

